### REGISTER
POST http://localhost:8000/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "first_name": "John",
  "last_name": "Doe",
  "password": "strongpassword123"
}

###

### LOGIN
POST http://localhost:8000/auth/login
Content-Type: application/x-www-form-urlencoded

username=test@example.com&password=strongpassword123

###

### GET CURRENT USER (needs token)
GET http://localhost:8000/users/me
Authorization: Bearer {{access_token}}

###

### CHANGE PASSWORD (needs token)
PUT http://localhost:8000/users/change-password
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "current_password": "strongpassword123",
  "new_password": "newpassword456",
  "new_password_confirm": "newpassword456"
}

###

### GET TODOS (needs token)
GET http://localhost:8000/tasks/
Authorization: Bearer {{access_token}}

###

### CREATE TODO (needs token)
POST http://localhost:8000/tasks/
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "description": "Buy milk",
  "due_date": "2025-07-13T20:00:00Z",
  "priority": 2
}

###

### GET TODO BY ID (needs token)
GET http://localhost:8000/tasks/{{todo_id}}
Authorization: Bearer {{access_token}}

###

### UPDATE TODO (needs token)
PUT http://localhost:8000/tasks/{{todo_id}}
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "description": "Buy oat milk",
  "due_date": "2025-07-15T12:00:00Z",
  "priority": 1
}

###

### MARK TODO AS COMPLETE (needs token)
PUT http://localhost:8000/tasks/{{todo_id}}/complete
Authorization: Bearer {{access_token}}

###

### DELETE TODO (needs token)
DELETE http://localhost:8000/tasks/{{todo_id}}
Authorization: Bearer {{access_token}}
